language: node_js
node_js:
  - "stable"
script:
  - npm script
notifications:
  email:
    - ghalcivar_13@outlook.com
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master

  
